language: objective-c
osx_image: xcode9
cache:
  directories:
  - Carthage

before_install:
  - curl -L -O https://github.com/Carthage/Carthage/releases/download/0.25.0/Carthage.pkg
  - sudo installer -pkg Carthage.pkg -target /
  - curl -L -O https://github.com/YPlan/CartfileDiff/releases/download/0.1/CartfileDiff.pkg
  - sudo installer -pkg CartfileDiff.pkg -target /
  - gem install fastlane --no-ri --no-rdoc --no-document

install: true
script: 
  - script/intelligent-bootstrap
  - fastlane scan -s Carthage-CI
